
   /*TIENE SUS OPERADORES IGUAL QUE  LOS DATOS(!,&,|,^),
        Y LOS NUMEROS INTERNAMENTE TRABAJAN EN BITS
                45 = 101101
        EL DESPLAZAMIENTO DE BITS A LA IZQUIERDA <<
                10101 << 2  ->  1010100
        EL DESPLAZAMIENTO DE BITS A LA DERECHA >>
                10101 >> 2  ->  00101 = 101

        PARA SABER SI UN BIT-N ESTÁ ACTIVO HACEMOS
        QUE 1 SE DESPLACE (N-VECES - 1) Y APLICAMOS
        AND & PARA QUE VOTE 1 O 0.
        Y ASÍ PODEMOS HACER OPERACIONES COMO QUERRAMOS
*/
